---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: observability-operator
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - list
- apiGroups:
  - monitoring.rhobs
  resources:
  - alertmanagers
  - prometheuses
  - servicemonitors
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks/finalizers
  - monitoringstacks/status
  verbs:
  - get
  - update
- apiGroups:
  - monitoring.rhobs
  resources:
  - monitoringstacks/status
  verbs:
  - get
  - update
- apiGroups:
  - monitoring.rhobs
  resources:
  - thanosqueriers
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.rhobs
  resources:
  - thanosqueriers/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.rhobs
  resources:
  - thanosqueriers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot
  - nonroot-v2
  resources:
  - securitycontextconstraints
  verbs:
  - use
